### ISSUE TITLE
Interactive jobs page (and several others) need to reflect loss of debug QOS

### ISSUE THREAD

**Issue by kkwinner** [ResearchComputing/Research-Computing-User-Tutorials#14]
on
https://github.com/ResearchComputing/Research-Computing-User-Tutorials/wiki/Interactive-Jobs#general-interactive-jobs
sample code and description need to be changed to reflect how to run an interactive job

from
https://docs.google.com/document/d/11FEq1nbqIlDpa1fmCf4WRZWLMSpxUMs6XGtNaw9LjCE/edit#
"New “testing” and “interactive” QOS, replacing “debug” QOS
A new “testing” QOS, with matching “shas-testing,” “sgpu-testing,” and “sknl-testing” partitions, will be introduced. Each user may submit one job using this QOS simultaneously, and each job is limited to 30 minutes. “shas-testing” jobs may use up to 24 CPUs but may allocate them from multiple nodes. Other “-testing” jobs are limited to one node.

A new “interactive” QOS will also be introduced, with a matching “shas-interactive” partition. Each user may submit one job using this QOS simultaneously, and each job is limited to 4 hours and 1 core.

Together, the “testing” and “interactive” QOS replace the “debug” QOS with a more formalized approach toward allocating resources for the intended use cases. The existing “shas,” “sgpu,” and “sknl” partitions will be limited to utilize less than the total number of nodes in the partition simultaneously to leave resources available for the new QOS.
Examples
sinteractive --qos interactive

**Comment by rctraining** [comment]
Went through the wiki and replaced debug with interactive or testing. Thanks for the post!

Daniel T.

**Comment by kkwinner** [comment]
Of course!  :)
*___________________________________________*
Kim Kanigel Winner, Ph.D.
UC Boulder Research Computing Analyst
Ronin Institute Research Scholar
<http://ronininstitute.org/research-scholars/kim-kanigel-winner/>
kim.kanigelwinner@colorado.edu
rattus8@gmail.com, kim.kanigelwinner@gmail.com
720-899-0945
~~~
“If we are happy, everybody looks up and shares our happiness.” ~Unknown
~~~
