### ISSUE TITLE
Load Balancer Tool Page: chmod needs to be added to example

### ISSUE THREAD

**Issue by kkwinner** [ResearchComputing/Research-Computing-User-Tutorials#16]
https://github.com/ResearchComputing/Research-Computing-User-Tutorials/wiki/The-Load-Balancer-Tool

In the example, 
$ chmod +x create_hello.sh
needs to be done before the sample script can be executed (new users will not know why example isn't working), between second and third code blocks

**Comment by rctraining** [comment]
Fixed. Thanks for the report!
