### ISSUE TITLE
Job submission page: "load module slurm" portion needs to be removed

### ISSUE THREAD

**Issue by kkwinner** [ResearchComputing/Research-Computing-User-Tutorials#17]

**Comment by kkwinner** [comment]
at:
https://github.com/ResearchComputing/Research-Computing-User-Tutorials/wiki/Job-Submissions

**Comment by rctraining** [comment]
Must've been required previously? Regardless the documentation has been adjusted.

**Comment by kkwinner** [comment]
Yes -- it was required before, and I believe it still works, but, def. not
required any longer!
*___________________________________________*
Kim Kanigel Winner, Ph.D.
16359 W. 10th Ave, R-4, Golden, CO 80401
Ronin Institute Research Scholar
<http://ronininstitute.org/research-scholars/kim-kanigel-winner/>
kimberly.kanigelwinner@ucdenver.edu
rattus8@gmail.com
720-899-0945 <javascript:void(0);>
~~~
“If we are happy, everybody looks up and shares our happiness.” ~Unknown
~~~
