### ISSUE TITLE
Matlab template changes

### ISSUE THREAD

**Issue by knuths** [ResearchComputing/Research-Computing-User-Tutorials#22]
This template actually doesn't make much sense here in its form.  I would remove the directory information (projects).  Also I would make note that parallel_std is the name of the .m program (ie, the Matlab program) that you would run.

**Comment by dtrahan41** [comment]
Adjusted the script to make more sense as a template, do you think it makes more sense?

**Comment by knuths** [comment]
Looks good to me.  Thanks!
