### ISSUE TITLE
Data Transfers page needs to explain how to populate Globus endpoint field with Summit

### ISSUE THREAD

**Issue by rctraining** [ResearchComputing/Research-Computing-User-Tutorials#23]
https://github.com/ResearchComputing/Research-Computing-User-Tutorials/wiki/Data-Transfers#globus

I had a CSU user have trouble with this, so maybe it's different for CSU accounts -- however, here is the content he needed that is not on the page (from INC0486845):

"So, once you have logged into Globus online, click either of the boxes labeled "Endpoint." If it is not already available as an endpoint, type 

CU Boulder Research Computing 

You will then need to log into that endpoint using your CSU credentials and a Duo push 

username: <eID>@colostate.edu 
password: <eIDPassword>,push 

Please give this a try and let me know if it opens up your Globus endpoint on Summit. "

Again -- not sure if this is different for CU users.....

**Comment by dtrahan41** [comment]
I believe the edits I made should remedy this issue. Not sure if the ambiguity was with the CSU login credentials or with the login credentials in general.
