### ISSUE TITLE
Error in sample job script on Load Balancer page

### ISSUE THREAD

**Issue by rctraining** [ResearchComputing/Research-Computing-User-Tutorials#24]
There is an error in the Load Balancer documentation.  It's probably fixed by the following change, but it might be worth checking with a Load Balancer expert:

In the sbatch submission script near the bottom of the page, the line
mpirun lb cmd_file

Should be changed to
mpirun lb lb_cmd_file

This should require the least effort. As the page is written, it is probably very confusing to users....

"lb" is also called before the file name in the Load Balancer README, here:
https://github.com/t-brown/lb/blob/master/README.md

**Comment by dtrahan41** [comment]
Good catch! Made the adjustments.
