### ISSUE TITLE
Job Script Page

### ISSUE THREAD

**Issue by feathern** [ResearchComputing/Research-Computing-User-Tutorials#8]
I suggest that we add a page describing the essential components of a batch script.

**Comment by rctraining** [comment]
Got it. Is it fine in job submissions, or should I just make a whole new page?

**Comment by feathern** [comment]
I think it's fine in the job submissions page.  If it seems too lengthy, we can always break it out into a separate page.

**Comment by rctraining** [comment]
Awesome ill have it done asap
